# Generated by Django 5.0.6 on 2024-06-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkieapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='location',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='fullname',
            field=models.CharField(max_length=255),
        ),
    ]
