# Generated by Django 5.0.6 on 2024-06-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkieapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordmodel',
            name='trans_language',
            field=models.URLField(default='http;//example.com'),
            preserve_default=False,
        ),
    ]
