# Generated by Django 5.0.6 on 2024-06-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkieapi', '0002_recordmodel_trans_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='language',
            field=models.CharField(default='en-NG', max_length=10),
        ),
    ]
