# Generated by Django 5.0.6 on 2024-06-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkieapi', '0002_rename_location_usermodel_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_image',
            field=models.ImageField(default=None, upload_to='profile_images/'),
        ),
    ]
