# Generated by Django 5.0.6 on 2024-06-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkieapi', '0003_alter_usermodel_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='contact_list',
            field=models.CharField(default='[]', max_length=2000),
        ),
    ]
