# Generated by Django 5.0.6 on 2024-06-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkieapi', '0004_usermodel_contact_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='contact_list',
            field=models.CharField(default='[]', max_length=200000),
        ),
    ]
