# Generated by Django 5.0.6 on 2024-06-20 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkieapi', '0005_alter_usermodel_contact_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='contact_list',
        ),
        migrations.CreateModel(
            name='PairModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('receiver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='walkieapi.usermodel')),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='walkieapi.usermodel')),
            ],
        ),
    ]
