# Generated by Django 5.0.6 on 2024-06-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkieapi', '0008_recordmodel_delivered_recordmodel_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordmodel',
            name='audio_file',
            field=models.URLField(),
        ),
    ]
