# Generated by Django 5.0.6 on 2024-06-23 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkieapi', '0009_alter_recordmodel_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordmodel',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_sender', to='walkieapi.usermodel'),
        ),
    ]
