# Generated by Django 5.0.6 on 2024-06-26 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkieapi', '0010_alter_recordmodel_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairmodel',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='walkieapi.usermodel'),
        ),
        migrations.AlterField(
            model_name='pairmodel',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='walkieapi.usermodel'),
        ),
    ]
