# Generated by Django 5.0.6 on 2024-06-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkieapi', '0011_alter_pairmodel_receiver_alter_pairmodel_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairmodel',
            name='block',
            field=models.BooleanField(default=False),
        ),
    ]
