# Generated by Django 5.0.6 on 2024-06-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkieapi', '0012_pairmodel_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairmodel',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
