# Generated by Django 5.0.6 on 2024-06-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkieapi', '0013_pairmodel_delivered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pairmodel',
            old_name='delivered',
            new_name='receiver_delivered',
        ),
        migrations.AddField(
            model_name='pairmodel',
            name='sender_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
