# Generated by Django 5.0.6 on 2024-06-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkieapi', '0015_remove_pairmodel_receiver_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairmodel',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
